spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ipdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    database: 0
    host: 192.168.10.110
    port: 6379
    password: 123456   # 密码（默认为空）
    timeout: 10000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: 100ms
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: analyze-svc

svc:
  hostname: 192.168.10.120 # 服务器ip
  ipv6:
    hostname: fe80::20c:29ff:fe4b:763a # 服务器ipv6
es:
  hostname: 192.168.10.120 # ES ip
  port: 9200 # ES端口
  scheme: http # 传输协议
  #  按需修改
  index-name: pb-7.15.1- # 索引名称
  loop-millisecond: 10000 # 多少ms循环一次 10s
  loop-longer-millisecond: 300000 # 多少ms循环一次 5min
  delete-hour: 6 # redis过期时间 6h
  buffer-millisecond: 5000 # 缓冲时间，预留出采集+传输+分析+显示的时间，5s
  dangerous-num: 2 # 超过多少条算危险ip
  dangerous-frequent: 2 # 超过次条算危险ip
  geoip-mmdb-path: D:\\Download_Code\\GeoLite2-Country_20230307\\GeoLite2-Country.mmdb # 三方GEOIP文件位置
  keyword:
    client-ip: client.ip.keyword
    group: clientGroup
